apiVersion: v1                                                                              
kind: Template
metadata:
  name: Jenkins Agent Template
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins-newman-agent
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins-selenium-agent
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: jenkins-newman-agent
    spec:
      source:
        git:
          uri: "https://github.com/vgonzalezo/jenkins-biq-agents"
          ref: master
      output:
        to:
          kind: ImageStreamTag
          name: 'jenkins-newman-agent:latest'
      strategy:
        dockerStrategy:
          dockerfilePath: newman.Dockerfile
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: jenkins-selenium-agent
    spec:
      source:
        git:
          uri: "https://github.com/vgonzalezo/jenkins-biq-agents"
          ref: master
      output:
        to:
          kind: ImageStreamTag
          name: 'jenkins-selenium-agent:latest'
      strategy:
        dockerStrategy:
          dockerfilePath: selenium.Dockerfile
parameters: []