kind: BuildConfig
apiVersion: v1
metadata:
  name: jenkins-newman-agent
spec:
  source:
    git:
      uri: "https://github.com/vgonzalezo/jenkins-biq-agents"
      ref: master
  output:
    to:
      kind: ImageStreamTag
      name: 'jenkins-newman-agent:latest'
  strategy:
    dockerStrategy:
      dockerfilePath: newman.Dockerfile